version: "3"
services:
  mysql8:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      # 端口映射,外部映射端口:13316
      - 13316:3306